# Generated by Django 4.0.4 on 2023-06-17 05:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maturity', models.PositiveSmallIntegerField()),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now, null=True)),
            ],
        ),
    ]
