# Generated by Django 4.0.4 on 2023-06-13 09:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('replica', 'レプリカ'), ('test', 'テスト'), ('production', '本番')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='tomato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('red', models.PositiveSmallIntegerField()),
                ('green', models.PositiveSmallIntegerField()),
                ('blue', models.PositiveSmallIntegerField()),
                ('date_time', models.DateTimeField(default=datetime.datetime(2023, 6, 13, 18, 34, 55, 305045))),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datas.crop')),
            ],
            options={
                'verbose_name_plural': 'tomatoes',
            },
        ),
        migrations.CreateModel(
            name='judgement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.BooleanField()),
                ('date_time', models.DateTimeField(default=datetime.datetime(2023, 6, 13, 18, 34, 55, 305045))),
                ('forecast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datas.crop')),
            ],
        ),
    ]
