# Generated by Django 4.0.4 on 2023-11-04 03:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('replica', 'レプリカ'), ('test', 'テスト'), ('production', '本番')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tomato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('red', models.PositiveSmallIntegerField()),
                ('green', models.PositiveSmallIntegerField()),
                ('blue', models.PositiveSmallIntegerField()),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datas.crop')),
            ],
            options={
                'verbose_name_plural': 'tomatoes',
            },
        ),
        migrations.CreateModel(
            name='Judgement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.BooleanField()),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('forecast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datas.crop')),
            ],
        ),
    ]
