# Generated by Django 4.0.4 on 2023-06-13 09:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judgement',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 13, 18, 36, 27, 402428)),
        ),
        migrations.AlterField(
            model_name='tomato',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 13, 18, 36, 27, 402428), null=True),
        ),
    ]
