# Generated by Django 4.0.4 on 2023-06-13 09:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datas', '0002_alter_judgement_date_time_alter_tomato_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judgement',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 13, 18, 56, 20, 809851)),
        ),
        migrations.AlterField(
            model_name='tomato',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
    ]
