# Generated by Django 4.0.4 on 2023-06-13 11:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datas', '0003_alter_judgement_date_time_alter_tomato_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judgement',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
    ]
