# Generated by Django 4.0.4 on 2023-06-13 11:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datas', '0004_alter_judgement_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judgement',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 13, 20, 57, 45, 334707), null=True),
        ),
        migrations.AlterField(
            model_name='tomato',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 13, 20, 57, 45, 333707), null=True),
        ),
    ]
