# Generated by Django 4.0.4 on 2023-06-13 12:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('datas', '0005_alter_judgement_date_time_alter_tomato_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judgement',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='tomato',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
